[Date]
date.timezone = Asia/Taipei

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2

expose_php = Off
disable_functions = exec, system, shell_exec, passthru, eval, popen, putenv, phpinfo
