server {
    listen 80;
    server_name localhost;

    #ssl_certificate /etc/letsencrypt/live/bopoki.ebrainzone.com/fullchain.pem;
    #ssl_certificate_key /etc/letsencrypt/live/bopoki.ebrainzone.com/privkey.pem;

    index index.php index.html;
    root /var/www/html/public;

    location / {
        proxy_set_header X-Forwarded-Proto $scheme;  # ✅ 加在這裡
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass chacha_app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}

